#!/bin/bash

: ${GITHUB_TOKEN:?"ENV VAR GITHUB_TOKEN is not set."}

cp index.bs .index.bs
if [ $? -ne 0 ] ; then
    exit $?;
fi
git checkout index.bs
bikeshed -f spec --gh-token=$GITHUB_TOKEN
cp .index.bs index.bs
if [ $? -ne 0 ] ; then
    exit $?;
fi
rm .index.bs
