# Workflow based on the w3c/spec-prod action example to deploy to W3C using Echidna:
# https://github.com/w3c/spec-prod/blob/main/docs/examples.md#deploy-to-w3c-using-echidna

name: CI

on:
  pull_request: {}
  push:
    branches: [main]

jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          GH_PAGES_BRANCH: gh-pages
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          # Replace following with appropriate value. See options.md for details.
          W3C_WG_DECISION_URL: https://lists.w3.org/Archives/Public/public-device-apis/2021May/0008.html
          W3C_BUILD_OVERRIDE: |
            status: CRD
            shortname: generic-sensor
